theme: minima
title: Machine Learning
author: Gobi
email: gopicoc2401@gmail.com
description: Machine Learning Learning Journal
url: https://gopi2401.site/ML/
baseurl: "/ML"

plugins:
  - jekyll-feed
  - jekyll-seo-tag